### ISSUE TITLE
improvise code with better version of k-means

### ISSUE THREAD

**Issue by huedaya** [elybin/vogado-2016-segmentation-method#1]

**Comment by elybin** [comment]
![image](https://user-images.githubusercontent.com/4969689/80046099-c7322500-8533-11ea-8399-0a1e1c7f9df4.png)


from the picture above, we can see that `EMKM` it's ok enough!

**Comment by elybin** [comment]
![image](https://user-images.githubusercontent.com/4969689/80046443-d5347580-8534-11ea-8cfd-1541a202a05a.png)
there's EMKM-2 that slightly better too

_[Enhanced moving K-means (EMKM) algorithm for image segmentation](sci-hub.tw/10.1109/TCE.2011.5955230)_

**Comment by elybin** [comment]
![image](https://user-images.githubusercontent.com/4969689/80047265-2cd3e080-8537-11ea-8cc0-bebf059d60c9.png)

_[Variance based moving K-means algorithm](https://arxiv.org/ftp/arxiv/papers/1704/1704.02197.pdf)_

**Comment by elybin** [comment]
![Uploading image.png…]()

[source code ](https://www.mathworks.com/matlabcentral/fileexchange/45057-adaptive-kmeans-clustering-for-color-and-gray-image?focused=3818104&tab=function)
[reference](https://ieeexplore.ieee.org/abstract/document/5726679)

**Comment by elybin** [comment]
how to achieve the goal:
1. try to replicate built in matlab's k-means, until the result exactly the same.
2. modify that k-means into better k-means based on the paper. 
3. test it out.

**Comment by elybin** [comment]
_200504 :_ 

**few fact founded.**
- result of k-means will always changes due to random number of initial centroid point, except we determine it.
- 

**next challenge:** 
- trying to replicate k-means (with preset centroid point).
- compare both method (matlab's k-means & replica's k-means).

**last file :** 
- simple_kmeans_test.m

**Comment by elybin** [comment]
200528 :

**successfully set initial centroid**

next challenge: 
- visualize data

**Comment by elybin** [comment]
200528 : 

i think it's enough to visualize the data
![image](https://user-images.githubusercontent.com/4969689/83083739-1fb78d80-a0b1-11ea-873a-c15cc70b6822.png)


**next:**
- comparing built-in k-means and external k-means. this is really important because we can customized the k-means algoritm

**Comment by elybin** [comment]
200620 

i decided to convert all of my script from matlab into python, the main reason is the lack and too advanced documentation of matlab.

**Comment by elybin** [comment]
200623

i've convert ~60% of the code, which is great!

**Comment by elybin** [comment]
200624

comparing images: 
| paper | python |
|-------|---------|
| <img src="https://user-images.githubusercontent.com/4969689/85572198-fada1a00-b65e-11ea-8424-972be6cafbf4.png" alt="drawing" width="200"/>| <img src="https://user-images.githubusercontent.com/4969689/85572249-04fc1880-b65f-11ea-85dd-e3283aebcb47.png" alt="drawing" width="200"/>|

**Comment by elybin** [comment]
200627

continue the previous challenge,

**what already done and next objective**
- already code ~80%
- fixing k-means and the rest of the code
- check **pixel_labels** maybe getting wrong while converting into 2d array

**Comment by elybin** [comment]
200628

successfully did the k-means, and just need to complete post-processing step.

**what already done and next objective**
- already code ~85%
- matlab_strel_ball

**Comment by elybin** [comment]
200701 

finally finishing this challenge! time to continue changing some clustering method!

**Comment by elybin** [comment]
sdfsdf

**Comment by elybin** [comment]
asdasdad

**Comment by elybin** [comment]
test

**Comment by elybin** [comment]
200706

i decided to finish this issue due, challenge finished. 
next we need to do qualitative analysis
