### ISSUE TITLE
testing with ALL-IDB data and summarize 'em with box-and-whisker plot

### ISSUE THREAD

**Issue by huedaya** [elybin/vogado-2016-segmentation-method#5]
200707 1:45pm 

alright, we're going to test with actual data, I've got those data, and we're ready to test 'em. but, we need to create the automation script of course.

**Comment by elybin** [comment]
200707

![image](https://user-images.githubusercontent.com/4969689/86789877-04697600-c092-11ea-9be4-0a5ce52cfd2b.png)

this was a  satisfying result! it's time to write the proposal!
